version: "3.7"
services:
  app:
    build:
      context: ./docker
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    depends_on:
      - database


  web:
    build:
      context: ./docker
      dockerfile: nginx_local.dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8080:80"
    depends_on:
      - app


  database:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"
